language: node_js
node_js:
    - "8.1.4"
script:
    - echo "Deploying"
install:
    - npm install
    - npm install -g firebase-tools
after_success:
    - npm run build
    - firebase deploy --token $FIREBASE_TOKEN
